/** 
THIS FILE IS AUTOGENERATED
weeeeeeeeeee
steps --> 
1) Download Figma Theme Tokens from starter project in Figma via Design Tokens plugin.
2) Replace design-tokens.tokens.json with the new file.
3) In your console, run: yarn generate-token-json.
*/

/**
 * TYPOGRAPHY
 */

// typography interfaces
interface ITypographyStyles {
  fontSize: number;
  textDecoration: string;
  fontFamily: string;
  fontWeight: number;
  fontStyle: string;
  fontStretch: string;
  letterSpacing: number;
  lineHeight: number;
  paragraphIndent: number;
  paragraphSpacing: number;
  textCase: string;
}
export interface ITypography {
  heading1: ITypographyStyles;
  heading2: ITypographyStyles;
  heading3: ITypographyStyles;
  heading4: ITypographyStyles;
  heading5: ITypographyStyles;
  paragraph: ITypographyStyles;
}
export type TThemeTypographyKey = keyof ITypography;
export type TThemeTypographyVariant = ITypographyStyles;

// typography object
const typography: ITypography = {
  heading1: {
    fontSize: 48.83000183105469,
    textDecoration: "none",
    fontFamily: "Inter",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 58.596,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  heading2: {
    fontSize: 39.060001373291016,
    textDecoration: "none",
    fontFamily: "Inter",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 46.872,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  heading3: {
    fontSize: 31.25,
    textDecoration: "none",
    fontFamily: "Inter",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 37.5,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  heading4: {
    fontSize: 25,
    textDecoration: "none",
    fontFamily: "Inter",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 30,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  heading5: {
    fontSize: 20,
    textDecoration: "none",
    fontFamily: "Inter",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 24,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
  paragraph: {
    fontSize: 16,
    textDecoration: "none",
    fontFamily: "Inter",
    fontWeight: 400,
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: 0,
    lineHeight: 19.2,
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: "none",
  },
};

/**
 * SHARED THEME VALUES
 */

// Shared theme value interfaces
interface ISharedThemeValues {
  typography: ITypography;
  spacing: number[];
}

// Shared theme value object
const sharedThemeValues: ISharedThemeValues = {
  typography: typography,
  spacing: [0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64],
};

/**
 * COLORS
 */

// Color interfaces
type RGB = `rgb(${number}, ${number}, ${number})`;
type RGBA = `rgba(${number}, ${number}, ${number}, ${number})`;
type HEX = `#${string}`;
export type Color = RGB | RGBA | HEX;
export interface IPrimitiveColors {
  gray50: Color;
  gray100: Color;
  gray200: Color;
  gray300: Color;
  gray400: Color;
  gray500: Color;
  gray600: Color;
  gray700: Color;
  gray800: Color;
  gray900: Color;
  indigo50: Color;
  indigo100: Color;
  indigo300: Color;
  indigo400: Color;
  indigo500: Color;
  indigo600: Color;
  indigo700: Color;
  indigo800: Color;
  indigo900: Color;
}

export interface ICoreColors {
  background: Color;
  onbackground: Color;
  surface: Color;
  surfaceactive: Color;
  surfacedisabled: Color;
  surfacehover: Color;
  onsurface: Color;
  primary: Color;
  primaryactive: Color;
  primarydisabled: Color;
  primaryhover: Color;
  onprimary: Color;
}

export type TThemeColors = IPrimitiveColors & ICoreColors;
export type TThemeColorKey = keyof TThemeColors;

// Color Values
export const primitiveColors: IPrimitiveColors = {
  gray50: "#f9fafbff",
  gray100: "#f3f4f6ff",
  gray200: "#e5e7ebff",
  gray300: "#d1d5dbff",
  gray400: "#9ca3afff",
  gray500: "#6b7280ff",
  gray600: "#4b5563ff",
  gray700: "#374151ff",
  gray800: "#1f2937ff",
  gray900: "#111827ff",
  indigo50: "#eff3feff",
  indigo100: "#e0e7ffff",
  indigo300: "#a5b4fcff",
  indigo400: "#818cf8ff",
  indigo500: "#6366f1ff",
  indigo600: "#4f46e5ff",
  indigo700: "#3f40c2ff",
  indigo800: "#3730a3ff",
  indigo900: "#312e81ff",
};

export const lightThemeColors: ICoreColors = {
  background: "#e5e7ebff",
  onbackground: "#111827ff",
  surface: "#f3f4f6ff",
  surfaceactive: "#9ca3afff",
  surfacedisabled: "#6b7280ff",
  surfacehover: "#d1d5dbff",
  onsurface: "#111827ff",
  primary: "#3730a3ff",
  primaryactive: "#312e81ff",
  primarydisabled: "#4b5563ff",
  primaryhover: "#3f40c2ff",
  onprimary: "#f9fafbff",
};

export const darkThemeColors: ICoreColors = {
  onbackground: "#f9fafbff",
  onprimary: "#f9fafbff",
  onsurface: "#f9fafbff",
  primary: "#3730a3ff",
  surface: "#374151ff",
  background: "#111827ff",
  surfacehover: "#4b5563ff",
  primaryhover: "#3f40c2ff",
  primaryactive: "#312e81ff",
  surfaceactive: "#1f2937ff",
  primarydisabled: "#4b5563ff",
  surfacedisabled: "#6b7280ff",
};

export const coreColorsKeys = [
  "background",
  "surface",
  "onsurface",
  "onbackground",
  "primary",
  "onprimary",
  "primaryhover",
  "primaryactive",
  "surfacehover",
  "surfaceactive",
  "primarydisabled",
  "surfacedisabled",
];
export const typographyKeys = [
  "heading1",
  "heading2",
  "heading3",
  "heading4",
  "heading5",
  "paragraph",
];

/**
 * THEMES
 */

// Theme interface

export type TTheme = {
  colors: TThemeColors;
  typography: ITypography;
  spacing: number[];
};

// Theme objects
export const lightTheme: TTheme = {
  colors: {
    ...lightThemeColors,
    ...primitiveColors,
  },
  ...sharedThemeValues,
} as const;
export const darkTheme: TTheme = {
  colors: {
    ...darkThemeColors,
    ...primitiveColors,
  },
  ...sharedThemeValues,
} as const;
